# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af4ba25001f08cab01c5b2ea05387fbcc9a02d210159fa88346c4761cf54b14f111c864d46fe6f065774f604d9dfb5a331e8ccd55591d77b475479649df59cf3

test:
  secret_key_base: 6471e942305bafbba1930ee933658733553b45ca867e3c072b82589e4ef955e99cae690db45c4d789d5d14d1e08107eb255ad2c425bf4db9bf98d4e3ae958f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
